[package]
name = "cozorer"
version = "0.1.0"
authors = ["Mathieu Kerjouan"]
edition = "2021"

[lib]
name = "cozorer_nif"
path = "src/lib.rs"
crate-type = ["cdylib"]

[dependencies]
rustler = "0.29.1"
cozo = "0.7.2"
serde_json = "1.0.81" 
